### ISSUE TITLE
RBAC support for 1.6.x clusters

### ISSUE THREAD

**Issue by yukiman76** [nanit/kubernetes-rabbitmq-cluster#10]
in rabbitmq-0  logs getting error 
curl: (22) The requested URL returned error: 403 Forbidden
would you have an idea of the cause

**Comment by yukiman76** [comment]
Looks like it related to running 1.6 of k8s and the now integration of RBAC i cloned the repo, would you like a patch ?

**Comment by erez-rabih** [comment]
@yukiman76 The configuration is tested against a bare new K8s 1.6 cluster via minikube, which works as expected.
What issue are you describing here?

**Comment by yukiman76** [comment]
Looks like its missing some Rights when RBAC is enabled, i was getting 403 Forbidden when trying to reach out to config entries

**Comment by erez-rabih** [comment]
In that case a patch would be gratefully accepted

**Comment by yukiman76** [comment]
working on it now in my branch will submit a "non-breaking" patch when its ready

**Comment by erez-rabih** [comment]
Great. Please make sure the deployment succeeds when RBAC is not enabled on the cluster as I don't want to break backward compatibility

**Comment by yukiman76** [comment]
yes that will be the goal

**Comment by erez-rabih** [comment]
closed by #19
