### ISSUE TITLE
Kubernetes v1.8 - rabbitmq.config permission denied

### ISSUE THREAD

**Issue by zsojma** [nanit/kubernetes-rabbitmq-cluster#20]
Hello,

When I deployed the rabbitmq in kubernetes v1.8, rabbitmq-0 pod returned this error:

> /etc/rabbitmq/rabbitmq.config: Permision denied

The same configuration worked well in kubernetes v1.7.

Potential fix is to update the Dockerfile to add the following line after add of clusterer.config:

> RUN chmod 666 /etc/rabbitmq/*

**Comment by erez-rabih** [comment]
Thanks for the PR.
Can you provide more details about the failure in 1.8?
I wonder what difference makes the deployment succeed on 1.7 and fail on 1.8

**Comment by zsojma** [comment]
The issue is not probably linked with kubernetes but with docker itself as I see now. There was an accidental downgrade of docker to version 1.12.5-cs5, build f7aca07 during upgrade of kubernetes. So it makes more sense now.

Our IT didn't manage to upgrade the docker yet, so I cannot test it right now... I don't have any other details about the failure except what I wrote before, sorry. I will check if the issue remains or not when we will use docker 17.03 again.

**Comment by erez-rabih** [comment]
We're using `Server Version: 1.12.6` of docker and I see no such problem.

**Comment by erez-rabih** [comment]
I'm closing the issue due to inactivity.
If you still see the problem please re-open.
