### ISSUE TITLE
How do you solve this situation? Why does this happen

### ISSUE THREAD

**Issue by laster-bin** [nanit/kubernetes-rabbitmq-cluster#33]
[root@node01 kubernetes-rabbitmq-cluster]# kubectl get pod |grep rabbit                                                            
rabbitmq-0                              1/1       Running            0          18m
rabbitmq-1                              0/1       CrashLoopBackOff   8          18m
rabbitmq-2                              1/1       Running            2          18m

[root@node01 kubernetes-rabbitmq-cluster]# kubectl get svc |grep rab
rabbitmq               ClusterIP      10.111.1.199    <none>        5672/TCP,4369/TCP,25672/TCP   19m
rabbitmq-management    LoadBalancer   10.108.55.45    <pending>     15672:31449/TCP               19m

[root@node01 kubernetes-rabbitmq-cluster]# kubectl logs rabbitmq-1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16652    0 16652    0     0   246k      0 --:--:-- --:--:-- --:--:--  246k
ERROR: epmd error for host rabbitmq-1.rmq-cluster: nxdomain (non-existing domain)

[root@node01 kubernetes-rabbitmq-cluster]# kubectl exec rabbitmq-0 -- rabbitmqctl cluster_status 
Cluster status of node 'rabbit@rabbitmq-0.rmq-cluster' ...
[{nodes,[{disc,['rabbit@rabbitmq-0.rmq-cluster']}]},
 {running_nodes,['rabbit@rabbitmq-0.rmq-cluster']},
 {cluster_name,<<"rabbit@rabbitmq-0.rmq-cluster.kube-system.svc.cluster.local">>},
 {partitions,[]},
 {alarms,[{'rabbit@rabbitmq-0.rmq-cluster',[]}]}]

**Comment by mwiesmueller** [comment]
Hi..

i had the same issue.. There's a problem with your dns resolution in your cluster. 
See here for debug your problem:

https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by erez-rabih** [comment]
i'm closing this as it doesn't seem to be related specifically to rabbitmq
please re-open if required
